### ISSUE TITLE
Old logo still appears when loading simulations

### ISSUE THREAD

**Issue by Popolechien** [openzim/phet#26] opened 2017-02-13 07:13 UTC
I mean this logo: 
![screenshot_2017-02-12-22-12-41](https://cloud.githubusercontent.com/assets/21675885/22874078/5863f776-f1c4-11e6-867a-53a3c8af24f8.png)

**Comment by ISNIT0** [comment] 2017-02-13 08:02
That'll be fun - I'll take a look on Tuesday.

**Comment by ISNIT0** [comment] 2017-12-15 15:14
Looks like I forgot I said that...

**Comment by kelson42** [comment] 2020-03-29 10:11
@Popolechien Honestly I'm not really sure I want to fix that one.

First of all the logo appears in a few other places:
* Simulation thumbnail (a PNG)
* In each simulation on the bottom right corner.

Changing all of them is not really trivial... and I believe nobody really complained about that... So I would prefer to put it in "Won't fix". Does that sounds acceptable?

**Comment by Popolechien** [comment] 2020-03-29 10:37
The people at PhET did complain.

**Comment by kelson42** [comment] 2020-03-29 11:52
@Popolechien Ok, this is really complicated to do for the moment. I guess if we want to do this kind fine graned think, we would need to transform totally the scraper and regenerate all the simulations from their source code on Github... Maybe for a version 3.0 if the success of what we do is confirmed!

**Comment by Popolechien** [comment] 2020-03-29 17:17
Yeah - they asked a while back already, and I think they understand we're a small outfit. But it's good to have an answer at the ready if/when they ask why the trademarks haven't been separated as requested.

**Comment by kelson42** [comment] 2022-12-03 15:56
We have the same problem with the logo/menu in the bottom right corner of the intermediate panel. IMO, in both case we would benefit to just remove it.

**Closed** 2022-12-23 09:41 UTC
Labels: enhancement
